language: cpp
dist: trusty
notifications:
  email: false
before_install:
- sudo apt-get update
- sudo apt-get install -y cmake libnuma-dev libaio-dev libhwloc-dev libatlas-base-dev zlib1g-dev numactl
compiler:
- g++
script:
- mkdir -p build && cd build && cmake .. && make && cd ..
- make clean; make
- cd libsafs/unit-test && make test && cd ../..
- cd flash-graph/unit-test && make test
- cd ../release-test/ && ./run_release_test.sh
- cd ../..
- cd matrix/unit-test && make test && cd ../..
